### PR TITLE
title header fix - 101 Global

### PR DESCRIPTION
**Pull request by skarode96**

### CODE REVIEW

**Comment by skarode96** [comment]
@akshaykarode Kindly check the PR !

**Comment by akshaykarode** [comment]
> @akshaykarode Kindly check the PR !



> @akshaykarode Kindly check the PR !

**Comment by akshaykarode** [comment]
> @akshaykarode Kindly check the PR !

public/index.html is not the part of Landing Page. 
Refer **src/App.js**

**Comment by skarode96** [comment]
title
Check the title on browser tab !

**Pull request closed without merging**
